(ns app-creator.creator.defaults)

(def build "maven")
(def language "java")
(def boot-version "2.6.2")
(def group "com.example")
(def artifact "demo")
(def name "demo")
(def description "Demo project for Spring Boot")
(def package-name "com.example.demo")
(def packaging "jar")
(def java-version "11")
(def project-version "0.0.1-SNAPSHOT")
