(ns app-creator.creator.server.spring.defaults)

(def build "maven")
(def language "java")
(def boot-version "2.6.2")
(def group "com.example")
(def artifact "demo")
(def proj-name "demo")
(def description "Demo project for Spring Boot")
(def packaging "jar")
(def java-version "11")
(def project-version "0.0.1-SNAPSHOT")
(def deps '("validation" "web" "data-jpa" "lombok"))
